### ISSUE TITLE
Training notebook TypeError

### ISSUE THREAD

**Issue by Zestea** [Archivoice/Diff-SVC-notebooks#1]
Today I attempted to use the training notebook, and everything was going alright until I got to the cell labeled "Step 5: Training". Upon running it, I get the following error:
```
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "/content/diff-svc/training/task/base_task.py", line 234, in start
    trainer.fit(task)
  File "/content/diff-svc/utils/pl_utils.py", line 489, in fit
    self.optimizers, self.lr_schedulers = self.init_optimizers(model.configure_optimizers())
  File "/content/diff-svc/training/task/base_task.py", line 174, in configure_optimizers
    optm = self.build_optimizer(self.model)
  File "/content/diff-svc/training/task/SVC_task.py", line 65, in build_optimizer
    weight_decay=hparams['weight_decay'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/adamw.py", line 78, in __init__
    if not 0.0 <= lr:
TypeError: '<=' not supported between instances of 'float' and 'str'
```

**Comment by Archivoice** [comment]
It seems to be an issue of the lr value not being set as a string, which causes it to be set as 5e-4 instead of 0.0005, which, while being the same value, causes issues with Diff-SVC, we'll have this fixed by today.
