### ISSUE TITLE
Step 5: Training AttributeError: 'HifiGAN' object has no attribute 'device'

### ISSUE THREAD

**Issue by sumaliqinghua** [Archivoice/Diff-SVC-notebooks#27]
;33;muse_spk_id: False, ;33;muse_split_spk_id: False, ;33;muse_uv: False, ;33;muse_var_enc: False, ;33;muse_vec: False, 
;33;mval_check_interval: 1000, ;33;mvalid_num: 0, ;33;mvalid_set_name: valid, ;33;mvalidate: False, ;33;mvocoder: network.vocoders.hifigan.HifiGAN, 
;33;mvocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128, ;33;mwarmup_updates: 2000, ;33;mwav2spec_eps: 1e-6, ;33;mweight_decay: 0, ;33;mwin_size: 512, 
;33;mwork_dir: checkpoints/huji, 
| Mel losses: {'ssim': 0.5, 'l1': 0.5}
12/14 03:50:58 AM gpu available: True, used: True
| load 'model' from '/content/diff-svc/pretrain/opencpop.ckpt'.
| model Trainable Parameters: 39.915M
Validation sanity check:   0% 0/1 [00:00<?, ?batch/s]
sample time step:   0% 0/100 [00:00<?, ?it/s]
sample time step:   4% 4/100 [00:00<00:02, 32.05it/s]
sample time step:   8% 8/100 [00:00<00:02, 31.75it/s]
sample time step:  12% 12/100 [00:00<00:02, 33.70it/s]
sample time step:  16% 16/100 [00:00<00:02, 34.73it/s]
sample time step:  20% 20/100 [00:00<00:02, 35.29it/s]
sample time step:  24% 24/100 [00:00<00:02, 35.64it/s]
sample time step:  28% 28/100 [00:00<00:02, 35.94it/s]
sample time step:  32% 32/100 [00:00<00:01, 35.98it/s]
sample time step:  36% 36/100 [00:01<00:01, 36.20it/s]
sample time step:  40% 40/100 [00:01<00:01, 36.23it/s]
sample time step:  44% 44/100 [00:01<00:01, 36.18it/s]
sample time step:  48% 48/100 [00:01<00:01, 36.21it/s]
sample time step:  52% 52/100 [00:01<00:01, 36.24it/s]
sample time step:  56% 56/100 [00:01<00:01, 36.24it/s]
sample time step:  60% 60/100 [00:01<00:01, 36.30it/s]
sample time step:  64% 64/100 [00:01<00:00, 36.21it/s]
sample time step:  68% 68/100 [00:01<00:00, 36.35it/s]
sample time step:  72% 72/100 [00:02<00:00, 36.35it/s]
sample time step:  76% 76/100 [00:02<00:00, 36.29it/s]
sample time step:  80% 80/100 [00:02<00:00, 36.30it/s]
sample time step:  84% 84/100 [00:02<00:00, 36.29it/s]
sample time step:  88% 88/100 [00:02<00:00, 36.29it/s]
sample time step:  92% 92/100 [00:02<00:00, 36.24it/s]
sample time step:  96% 96/100 [00:02<00:00, 36.26it/s]
sample time step: 100% 100/100 [00:02<00:00, 35.89it/s]
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "/content/diff-svc/training/task/base_task.py", line 234, in start
    trainer.fit(task)
  File "/content/diff-svc/utils/pl_utils.py", line 495, in fit
    self.run_pretrain_routine(model)
  File "/content/diff-svc/utils/pl_utils.py", line 571, in run_pretrain_routine
    self.evaluate(model, self.get_val_dataloaders(), self.num_sanity_val_steps, self.testing)
  File "/content/diff-svc/utils/pl_utils.py", line 1192, in evaluate
    output = self.evaluation_forward(model,
  File "/content/diff-svc/utils/pl_utils.py", line 1316, in evaluation_forward
    output = model.validation_step(*args)
  File "/content/diff-svc/training/task/SVC_task.py", line 155, in validation_step
    self.plot_wav(batch_idx, sample['mels'], model_out['mel_out'], is_mel=True, gt_f0=gt_f0, f0=pred_f0)
  File "/content/diff-svc/training/task/SVC_task.py", line 218, in plot_wav
    gt_wav = self.vocoder.spec2wav(gt_wav, f0=gt_f0)
  File "/content/diff-svc/network/vocoders/hifigan.py", line 63, in spec2wav
    device = self.device
AttributeError: 'HifiGAN' object has no attribute 'device'

**Comment by sumaliqinghua** [comment]
oh i see, ocoder_ckpt is wrong
